select
    Customer_ID as customer_id,
    Gender as gender,
    Age as age,
    Married as is_married,
    State as state,
    Number_of_Referrals as number_of_referrals,
    Tenure_in_Months as tenure_in_months,
    Value_Deal as value_deal,
    Phone_Service as phone_service,
    Multiple_Lines as multiple_lines,
    Internet_Service as internet_service,
    Internet_Type as internet_type,
    Online_Security as online_security,
    Online_Backup as online_backup,
    Device_Protection_Plan as device_protection_plan,
    Premium_Support as premium_support,
    Streaming_TV as streaming_tv,
    Streaming_Movies as streaming_movies,
    Streaming_Music as streaming_music,
    Unlimited_Data as unlimited_data,
    Contract as contract,
    Paperless_Billing as paperless_billing,
    Payment_Method as payment_method,
    Monthly_Charge as monthly_charge,
    Monthly_Charge < 0 as has_negative_monthly_charge,
    Total_Charges as total_charges,
    Total_Refunds as total_refunds,
    Total_Extra_Data_Charges as total_extra_data_charges,
    Total_Long_Distance_Charges as total_long_distance_charges,
    Total_Revenue as total_revenue,
    Customer_Status as customer_status,
    Churn_Category as churn_category,
    Churn_Reason as churn_reason
from {{ source('bronze', 'customer_data') }}
